### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/v1/users

###
GET http://localhost:8080/v1/users/1

###
GET http://localhost:8080/v1/users/hello